### PR TITLE
Publish terminal status attribute

### LINKED ISSUE #13: Publish out 'status' attribute
It seems something like this would be helpful:

``` html
<kubernetes-container-terminal 
  status="status"></kubernetes-container-terminal>
```

It would be nice to have at least a `connected="true||false` published out, but perhaps a `status="some-string-status"` would be more useful?

For 'disconnected', I imagine we can update this in `line 197` via the `socket.on('close')`, or `line 154` in the `fatal()` func, or `line 207` in the `disconnect()` function.  

Thinking a bit about the best option, may PR it.  The initial goal is to be able to track when the terminal crashes/died unexpectedly & hook into this for other UI.

### PR DESCRIPTION
**Pull request by MarkDeMaria**
fixes #13 

Origin-web-console is making UI changes to how the user interacts with terminals to containers in a pod on openshift. In order to accurately reflect terminal state, a variable needed to be exposed to the view in order to make appropriate UI styling changes.

``` html
<div ng-repeat="term in containerTerminals">
     <kubernetes-container-terminal
          prevent="!terminalTabWasSelected"
          ng-if="term.isUsed"
          ng-show="term.isActive"
          pod="pod"
          container="term.name"
          status="term.status">
     </kubernetes-container-terminal>
</div>
```

@benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Nice.  @stefwalter cool with this update?

**Comment by jwforres** [comment]
@MarkDeMaria you'll need to run a grunt build of this and check in the dist file as well

**Comment by MarkDeMaria** [comment]
@jwforres @stefwalter 'grunt build' successfully.

**Comment by benjaminapetersen** [comment]
nice, i see the dist.

File: container-terminal.js [hunk 1]
```diff
@@ -82,9 +82,12 @@
                         rows: '=',
                         cols: '=',
                         screenKeys: '=',
-                        autofocus: '=?'
+                        autofocus: '=?',
+                        status: '='
```
Comment (jwforres) [inline container-terminal.js:86]: would be good to have a comment here explaining that it is not an input and that it is for reporting status back to the parent scope.

**Comment by jwforres** [comment]
otherwise the change LGTM

File: container-terminal.js (hunk 1 above)
Comment (benjaminapetersen) [inline container-terminal.js:86]: Probably should update README.md & document it.

**Comment by MarkDeMaria** [comment]
@jwforres Readme updated and comment added. Dist files updated as well.
